project:
  type: website

website:
  title: "Stephen Yu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: experience.qmd
        text: Experience
      - href: education.qmd
        text: Education
    right: 
      - icon: github
        menu: 
          - text: Website Source Code
            url: https://github.com/stephenyu2/stephen-website
          - text: Github Profile
            url: https://github.com/stephenyu2
  page-footer:
    right: "&copy; 2024, Stephen Yu"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute: 
  freeze: auto
